# Habilita o mouse (rolagem e clique)
# 1. Habilita o mouse
set -g mouse on

# 2. Conecta o tmux ao namespace do usuário (CORREÇÃO DO PROBLEMA)
set-option -g default-command "reattach-to-user-namespace -l zsh"

# 3. Configura para copiar ao soltar o mouse (para Cmd+V funcionar)
# Para modo VI (se você usa set-window-option -g mode-keys vi)
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Para modo padrão (caso não use VI keys)
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"


set-option -g history-limit 100000

set -g base-index 1

setw -g pane-base-index 1


bind c new-window -c '#{pane_current_path}'

# Divide a tela horizontalmente mantendo o diretório atual
bind '"' split-window -c "#{pane_current_path}"

# Divide a tela verticalmente mantendo o diretório atual
bind % split-window -h -c "#{pane_current_path}"


